### ISSUE TITLE
How to set full width in post page?

### ISSUE THREAD

**Issue by fengguangle** [peterhebert/simple-grey#1]
In the page of post detail or post list, when I do't need any widget, there is one emty area on right.
how to fix it?

**Comment by peterhebert** [comment]
Fixed by #2 - the theme now adds classes to the body tag for each active sidebar. The column no longer appears if the sidebar does not contain any widgets. Added new release [1.4.4](https://github.com/peterhebert/simple-grey/releases/tag/1.4.4). I've also pushed this release to WordPress theme directory, should appear shortly.

**Comment by fengguangle** [comment]
I already update to version 1.4.4.
But no any changes.
Any setting options?

update:
Maybe have some changes.
Now there is only one row when no secondary widget.

But  the width of custom page  is different from the width of post list page or post detail page.
The Row width is 1200 in sample-page, but the home page(post list) is 1500. both no widget.

I understand, in custom css,I add
`.wrap {
  max-width: 60em;
}`
That can make every page having same width.

**Comment by peterhebert** [comment]
The default page template is set to have a maximum width of 60em, and show the secondary sidebar below the main content area. This was done to have optimum line length.

As this may be a bit confusing, I will move this styling to a separate page template (Single Column Narrow) in the next point release (1.5.0), and have the default page template work the same as the posts pages, with the secondary sidebar moving to the right at the breakpoint of 60em and wider. That way the default page keeps the same 1500 width as the rest of the post and archive templates.

**Comment by fengguangle** [comment]
I agree with your change, for a website, style unification is critical.
1500 width may not apply to some users. So  you can add some custom setting options within the theme customization. Or these custom features are included in a paid version , maybe named Simple-Grey Pro. haha :)
In my opinion, this is a very good theme, simple, fast, beautiful, comfortable.
I like it, thank you for your work.

**Comment by peterhebert** [comment]
I have standardized on the 75em max width as the theme is designed to work well on mobile through larger (4k) desktop monitors. At larger breakpoints (1600px, 2400px, 3200px), the base text size also gets bumped up (1.25x, 1.5x, 2x) to deal with retina displays. 

The new single column narrow template has been included in release [1.5.0](https://github.com/peterhebert/simple-grey/releases/tag/1.5.0).

As for a premium version of this theme, it is not something I have plans for at the moment. You can always customise the CSS via the LESS pre-processor files - available in this GitHub repo. You could fork this project as well to make your own custom version. I welcome pull requests.

**Comment by fengguangle** [comment]
I am not very good at web development, so I do not understand the real reasons for some of the problems, but I can submit issues.
