### ISSUE TITLE
Latest versions continue to crash with PHP errors (repost from WP theme support page)

### ISSUE THREAD

**Issue by liny-fox** [peterhebert/simple-grey#21]
Hi,

With the latest update website crashed:

Parse error: syntax error, unexpected ‘)’ in /wp-content/themes/simple-grey/inc/template-tags.php on line 211

Server is running php 7.2.34.

Anyone has similar experience?

(Above is copy paste from [here](https://wordpress.org/support/topic/update-1-7-2-crashed-the-website/))

**Comment by liny-fox** [comment]
Can confirm the error still exists in 1.7.7.
PHP version PHP 7.2.24-0ubuntu0.18.04.11
PHP Parse error:  syntax error, unexpected ')' in /var/www/html/wp/wp-content/themes/simple-grey/inc/template-tags.php on line 200,
The latest version that works is 1.7.0 for me, anything newer crashes.

**Comment by peterhebert** [comment]
Pushed a fix with the PR. Relaease 1.7.8 now published on GitHub and in WordPress theme directory.

**Comment by liny-fox** [comment]
Thank you, can confirm the problem is gone and I can finally update the theme and not stare at the 1 available update that I kept forgetting to report.
