### ISSUE TITLE
This theme may cause article editor issues

### ISSUE THREAD

**Issue by fengguangle** [peterhebert/simple-grey#3]
When activate this theme(version 1.4.4), the  height of article text editor has been increasing when click the edit area or some other operation.
The editor I'm talking about is article editor  in admin panel.
Some error in edit-stye.css? I don't know. But any other theme don't have this problem.

WP version:  4.8
Browser: Chrome

**Comment by peterhebert** [comment]
@fengguangle Please post a screenshot of the issue, compare Simple Grey with Twenty Seventeen.

**Comment by fengguangle** [comment]
@peterhebert  OK

**1.simple-grey theme**
[screenshot-1 with some error](http://tinypic.com/r/2vb7wpe/9)

**2.Twenty Seventeen theme**
[screenshot-2 with no error](http://tinypic.com/r/2yl7ehj/9)

You can look at the height changes in the editing area.
And I'm not sure that's the reason of theme. You can test to determine if it's my own problem.

## **update:**
when click edit area or toggle tab, height consistency in the increase.
[Height Property Position screenshot ](http://tinypic.com/r/1f9zxi/9)

I don't know if you can see the image. Because I can't upload picture on this comment of github editor.
;(

The position of HTML source code:
`<iframe id="content_ifr" frameborder="0" allowtransparency="true" title="富文本区域。按Alt-Shift-H获取帮助。" style="width: 100%; height: 342px; display: block;"></iframe>`

Height Property Position:
`element.style {
    width: 100%;
    height: 342px;
    display: block;
}`

**Comment by peterhebert** [comment]
turns out that having a height property against either the `<html>` or `<body>` tags causes this issue in tinymce - this is a [known issue](https://github.com/ProjectCleverWeb/Semantic-UI-WordPress/issues/32). I have removed the height properties from `<html>` and `<body>` in the editor css and it resolves the problem. Fix in #4
