### ISSUE TITLE
The post page can't load normally when there is only one post

### ISSUE THREAD

**Issue by fengguangle** [peterhebert/simple-grey#5]
When there is only one article post,such as only one "Hello world",there is no comment area for the article detail page.

And another doubt:
How to use the archive.php to build a archive page?

**Comment by peterhebert** [comment]
Turns out that thee was an error with the way I was displaying the posts navigation that caused this to break display of comments. Also messed up the display of the admin bar on single posts.

**Comment by peterhebert** [comment]
Fixed by release [1.5.1](https://github.com/peterhebert/simple-grey/releases/tag/1.5.1)
